import os
import random # Required for simulating test data
# Cleaned up imports, removing commented lines
from src.etl.utils import create_entry_template, append_entry

def main():
    data_path = "data/journal_entries.jsonl"
    
    # --- Data Creation & Integrity Fixes ---
    entry = create_entry_template()
    
    # 1. Inject simulated data for better testing utility
    topics = ["Python", "Machine Learning", "Data Engineering", "DataSelf", "Career"]
    entry["title"] = f"Template Entry - {random.choice(topics)} Focus"
    entry["topic_tags"] = [random.choice(topics)]
    entry["reflection"] = "This is a placeholder reflection generated by the template script for pipeline testing."
    entry["mood"] = random.choice(["happy", "curious", "neutral"])
    entry["energy"] = random.randint(5, 10)
    
    # 2. Update source tag to reflect automated template creation
    entry["source"] = "template_script" 
    
    # --- Directory Handling and Appending ---
    if not os.path.exists("data"):
        os.makedirs("data")
        
    append_entry(data_path, entry)
    print("✅ New entry template appended to data/journal_entries.jsonl")

if __name__ == "__main__":
    main()